version: '3.8'

services:

  db:
    image: postgres:12.4
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: on-failure
    env_file:
      - ./.env

  frontend:
    image: maxbstr/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/build/

  backend:
    image: maxbstr/foodgram_backend:latest
    expose:
      - 8000
    command: bash -c "
        python manage.py makemigrations  --no-input &&
        python manage.py migrate --no-input &&
        gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
        "
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/code/backend_static/
      - media_value:/code/backend_media/
    env_file:
      - ./.env

  openssl:
    build:
      context: openssl/
    command: /usr/local/openssl/bin/openssl req -x509 -nodes -days 365 -subj "/C=CA/ST=QC/O=Company, Inc./CN=mydomain.com" -addext "subjectAltName=DNS:mydomain.com" -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt
    volumes:
      - ./openssl:/etc/ssl/private/nginx-selfsigned.key
      - ./openssl:/etc/ssl/certs/nginx-selfsigned.crt

  nginx-proxy:
    image: nginx:1.19.3
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - static_value:/code/backend_static/
      - media_value:/code/backend_media/

      - ./openssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./openssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    restart: always
    depends_on:
      - openssl
      - backend
      - frontend


volumes:
  postgres_data:
  static_value:
  media_value: